---
title: "Tercera tarea"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: journal
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r carga-paquetes, message=FALSE, warning=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(plotly)
library(sf)
library(DT)
library(readxl)
library(leaflet)
library(stringi)
```

```{r carga-datos-cantones, message=FALSE, warning=FALSE}
cantones <-
  st_read(dsn = "cantones_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)
```

```{r carga-datos-delitos, message=FALSE, warning=FALSE}
estadisticas <- read_xls(path="estadisticaspoliciales2021.xls")
estadisticas=subset(estadisticas, select=c("Delito", "Fecha", "Victima", "Edad", "Genero", "Provincia", "Canton"))
```


Column {data-width=150}
-----------------------------------------------------------------------

### Mapa con leaflet de coropletas
**Fuente de los datos: [Instituto Geográfico Nacional (IGN)](https://www.snitcr.go.cr/ign_ign) y [Organismo de Investigación Judicial (OIJ)](https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos) **

```{r, message=FALSE, warning=FALSE}
cantones <-
  cantones %>%
  mutate(canton_normalizado = tolower(stri_trans_general(canton, id = "Latin-ASCII")))

estadisticas <-
  estadisticas %>%
  mutate(canton_normalizado = tolower(stri_trans_general(Canton, id = "Latin-ASCII")))
```

```{r, message=FALSE, warning=FALSE}
estadisticas <-
  estadisticas %>%
  left_join(
    dplyr::select(
      st_drop_geometry(cantones),
      cod_canton,
      canton_normalizado
    ),
    by = "canton_normalizado",
    copy = FALSE,
    keep = FALSE
  )
```

```{r, message=FALSE, warning=FALSE}
delitos_x_canton <-
  estadisticas %>%
  count(cod_canton, name = "estadisticas")

cantones_delitos <-
  cantones %>%
  left_join(
    delitos_x_canton,
    by = "cod_canton",
    copy = FALSE,
    keep = FALSE
  )
```

```{r, paleta_color, message=FALSE, warning=FALSE}
colores_cantones_delitos <-
  colorNumeric(palette = "Reds",
               domain = cantones_delitos$delitos,
               na.color = "transparent")
```

```{r, mapa_coropletas, message=FALSE, warning=FALSE}
leaflet() %>%
  setView(
    lng = -84.19452,
    lat = 9.572735,
    zoom = 7) %>%
  addTiles(group = "OpenStreetMap") %>% 
  addPolygons(
    data = cantones_delitos,
    fillColor = ~ colores_cantones_delitos(cantones_delitos$estadisticas),
    fillOpacity = 0.8,
    color = "black",
    stroke = TRUE,
    weight = 1.0,
    popup = paste(
      paste(
        "<strong>Cantón:</strong>",
        cantones_delitos$canton
      ),
      paste(
        "<strong>Delitos:</strong>",
        cantones_delitos$estadisticas
      ),
      sep = '<br/>'
    ),
    group = "Delitos en cantones"
  ) %>%
  addLayersControl(
    # control de capas
    baseGroups = c("OpenStreetMap"),
    overlayGroups = c("Delitos en cantones")
  ) %>%
  addLegend(
    # leyenda
    position = "bottomleft",
    pal = colores_cantones_delitos,
    values = cantones_delitos$estadisticas,
    group = "Delitos",
    title = "Cantidad de delitos"
  )
```


Column {data-width=150}
----------------------------------------------------------------------

### Tabla con DT


```{r, message=FALSE, echo=FALSE, warning=FALSE}
estadisticas %>%
  datatable(options = list(
    pageLength = 5,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json') 
  ), colnames=c("Delito", "Fecha", "Víctima", "Edad", "Género", "Provincia", "Cantón"))
```


Column {data-width=150}
-----------------------------------------------------------------------

### Cantidad de delitos por tipo de delito

```{r, grafico_simple, message=FALSE, echo=FALSE, warning=FALSE}
tabla=summarise(group_by(estadisticas,Delito),
                n=n())

ggplot2_cantidad_delitos <- 
  ggplot(tabla,aes(y=reorder(Delito,+n),x=n)) +
  geom_bar(stat = "identity",fill=c(1:6)) +
  ggtitle("Cantidad de delitos por tipo de delito") +
  ylab("Delito") +
  xlab("Cantidad de delitos") +
  theme_classic()

ggplotly(ggplot2_cantidad_delitos) %>% config(locale = 'es')
```


### Cantidad de delitos por víctima
```{r}
tabla4=summarise(group_by(estadisticas, Victima),
                n=n())
ggplot2_cantidad_delvic <- 
  ggplot(tabla4,aes(y=reorder(Victima,+n), x=n)) +
  geom_bar(stat = "identity", fill=c(6:10)) +
  ggtitle("Cantidad de delitos por víctima") +
  ylab("Tipo de víctima") +
  xlab("Cantidad de delitos") +
  theme_classic()

ggplotly(ggplot2_cantidad_delvic) %>% config(locale = 'es')
```


Column {data-width=140}
-----------------------------------------------------------------------


### Cantidad de delitos por mes del año

```{r, delito_mes, message=FALSE, echo=FALSE, warning=FALSE}
estadisticas$fecha2=as.numeric(format(estadisticas$Fecha,"%m"))
tabla1=summarise(group_by(estadisticas, fecha2),
                n=n())
ggplot2_cantidad_delitos <- 
  ggplot(tabla1,aes(x=fecha2, y=n)) +
  geom_bar(stat = "identity", fill=4) +
  ggtitle("Cantidad de delitos por mes") +
  ylab("Cantidad de Delito") +
  xlab("Mes") +
  scale_x_continuous(breaks = c(1:11),labels = c("Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Set","Oct","Nov"))+
  theme_classic()

ggplotly(ggplot2_cantidad_delitos) %>% config(locale = 'es')
```



### Proporción de Tipo de delitos por género

```{r, delito_genero, message=FALSE, echo=FALSE, warning=FALSE}

ggplot2_barras_apiladas_cantidad <-
  estadisticas %>%
  ggplot(aes(x = estadisticas$Delito, fill = estadisticas$Genero)) +
  geom_bar(position = "fill") +
  ggtitle("Proporción de Tipo de delitos por género") +
  xlab("Tipo de Delito") +
  ylab("Proporción") +
  labs(fill = "Género") +
  theme_classic()+
  coord_flip()

ggplotly(ggplot2_barras_apiladas_cantidad) %>% config(locale = 'es')
```





